project_name: "Image Power Tools"
tagline: "Spend more time making games. Less time managing images."
project_url: "https://github.com/aschearer/image-powertools"
latest_release_url: "https://github.com/aschearer/image-powertools/releases/latest"