version: 1.0.{build}
skip_tags: true
configuration:
- Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a image-powertools.zip "%APPVEYOR_BUILD_FOLDER%\PowerTools.CommandLine\bin\Release\*.dll" "%APPVEYOR_BUILD_FOLDER%\PowerTools.CommandLine\bin\Release\*.exe" "%APPVEYOR_BUILD_FOLDER%\PowerTools.CommandLine\bin\Release\*.txt" "%APPVEYOR_BUILD_FOLDER%\PowerTools.CommandLine\bin\Release\*.md"
artifacts:
- path: image-powertools.zip
  name: image-powertools.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 6pCLvKt9/2YfMv4pRwtkFrizsnAsKICCQcAJW+aztA6D899r31YH/i2c+NtsdomL
  artifact: image-powertools.zip