version: 1.0.{build}
branches:
  only:
    - master
  except:
    - gh-pages
configuration:
- Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  verbosity: minimal
  project: Source\PowerTools.sln
after_build:
- cmd: 7z a image-powertools.zip "%APPVEYOR_BUILD_FOLDER%\Source\PowerTools.CommandLine\bin\Release\*.dll" "%APPVEYOR_BUILD_FOLDER%\Source\PowerTools.CommandLine\bin\Release\*.exe" "%APPVEYOR_BUILD_FOLDER%\PowerTools.CommandLine\bin\Release\*.txt" "%APPVEYOR_BUILD_FOLDER%\Source\PowerTools.CommandLine\bin\Release\*.md"
artifacts:
- path: image-powertools.zip
  name: image-powertools.zip